### ISSUE TITLE
Wrong version of @types/node

### ISSUE THREAD

**Issue by munierujp** [tan-z-tan/GitHubGuessr#10]
The version of @types/node should be 18.8.x because Node version is 18.8.0.

https://github.com/tan-z-tan/GitHubGuessr/blob/20b942ad1d4e4518cdc468b1d6b4eeb614560acf/package.json#L30

https://github.com/tan-z-tan/GitHubGuessr/blob/20b942ad1d4e4518cdc468b1d6b4eeb614560acf/.node-version#L1

cf. https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library

**Comment by tan-z-tan** [comment]
@munierujp oh... I didn't notice😂
Will fix it.Thank you!

**Comment by tan-z-tan** [comment]
Fixed it! (Committed to master by mistake)
https://github.com/tan-z-tan/GitHubGuessr/commit/aa8e5a6189739c4b73ebbbd4ce8b929c53412660
